### ISSUE TITLE
marqLevAlgParallel installs as marqLevAlg

### ISSUE THREAD

**Issue by abureau** [VivianePhilipps/marqLevAlgParallel#1]
The package name in the DESCRIPTION file is marqLevAlg, not marqLevAlgParallel. So the following commands within R return an error.

devtools::install_github("VivianePhilipps/marqLevAlgParallel")
library(marqLevAlgParallel)
Error in library(marqLevAlgParallel) : 
  aucun package nommé ‘marqLevAlgParallel’ n'est trouvé

This is a problem when other functions require marqLevAlgParallel, such as CInLPN.estim from the CInLPN package. The examples for CInLPN do not work because of that.

**Comment by VivianePhilipps** [comment]
Hello,

we change the name of the package since the submission to CRAN. Actually, the package existed before the parallel addings under the name marqLevAlg and we did not want to have two different  packages. So the R package's name is now marqLevAlg, although the github directory is still called marqLevAlgParallel.

The packages that use the algorithm should change their dependencies. It has been done recently for the CInLPN package.

Thanks for your comment!

Viviane

**Comment by abureau** [comment]
Indeed, the CInLPN package has changed its dependency.

Merci.
